/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IVerifySignature,
  IVerifySignatureInterface,
} from "../IVerifySignature";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_ethSignedMessageHash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "_sig",
        type: "bytes",
      },
    ],
    name: "recover",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_signer",
        type: "address",
      },
      {
        internalType: "address",
        name: "_hotWallet",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_sig",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class IVerifySignature__factory {
  static readonly abi = _abi;
  static createInterface(): IVerifySignatureInterface {
    return new utils.Interface(_abi) as IVerifySignatureInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVerifySignature {
    return new Contract(address, _abi, signerOrProvider) as IVerifySignature;
  }
}
